[package]
name = "pixiv-down-re"
version = "0.2.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.9", features = ["json"] }
tokio = { version = "1.41.0", features = ["full"] }
serde_json = "1.0.132"
futures = "0.3.31"